# Generated by Django 6.0 on 2026-01-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='display_id',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
